/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};

/* T_fk:(i0[6])->(o0[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40;
  a00=arg[0]? arg[0][0] : 0;
  a01=cos(a00);
  a02=-9.9077979859924592e-01;
  a03=arg[0]? arg[0][1] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a06=1.3548206759838052e-01;
  a03=sin(a03);
  a07=(a06*a03);
  a05=(a05+a07);
  a07=(a01*a05);
  a00=sin(a00);
  a08=7.2786748251621915e-06;
  a09=(a08*a04);
  a10=2.6778982591969173e-06;
  a11=(a10*a03);
  a09=(a09+a11);
  a11=(a00*a09);
  a07=(a07-a11);
  a11=-2.2125743390361549e-01;
  a12=arg[0]? arg[0][2] : 0;
  a13=cos(a12);
  a14=(a11*a13);
  a15=9.7521543668175559e-01;
  a12=sin(a12);
  a16=(a15*a12);
  a14=(a14+a16);
  a16=(a07*a14);
  a06=(a06*a04);
  a02=(a02*a03);
  a06=(a06-a02);
  a02=(a01*a06);
  a10=(a10*a04);
  a08=(a08*a03);
  a10=(a10-a08);
  a08=(a00*a10);
  a02=(a02-a08);
  a08=-9.7521543668175559e-01;
  a17=(a08*a13);
  a18=(a11*a12);
  a17=(a17+a18);
  a18=(a02*a17);
  a16=(a16+a18);
  a18=arg[0]? arg[0][3] : 0;
  a19=cos(a18);
  a20=(a16*a19);
  a15=(a15*a13);
  a21=(a11*a12);
  a15=(a15-a21);
  a21=(a07*a15);
  a11=(a11*a13);
  a08=(a08*a12);
  a11=(a11-a08);
  a02=(a02*a11);
  a21=(a21+a02);
  a02=-3.6732051033465739e-06;
  a18=sin(a18);
  a08=(a02*a18);
  a12=(a21*a08);
  a20=(a20+a12);
  a12=6.8487567845754728e-06;
  a13=(a12*a01);
  a22=9.9999999996992484e-01;
  a23=(a22*a00);
  a13=(a13-a23);
  a23=9.9999999999325373e-01;
  a24=(a23*a18);
  a25=(a13*a24);
  a20=(a20+a25);
  a25=arg[0]? arg[0][4] : 0;
  a26=cos(a25);
  a27=(a20*a26);
  a28=(a02*a19);
  a29=(a21*a28);
  a30=(a16*a18);
  a29=(a29-a30);
  a30=(a23*a19);
  a31=(a13*a30);
  a29=(a29+a31);
  a25=sin(a25);
  a31=(a02*a25);
  a32=(a29*a31);
  a27=(a27+a32);
  a32=-9.9999999999325373e-01;
  a33=(a32*a21);
  a13=(a02*a13);
  a33=(a33+a13);
  a13=(a32*a25);
  a34=(a33*a13);
  a27=(a27+a34);
  a34=arg[0]? arg[0][5] : 0;
  a35=cos(a34);
  a36=(a27*a35);
  a37=(a02*a26);
  a38=(a29*a37);
  a20=(a20*a25);
  a38=(a38-a20);
  a20=(a32*a26);
  a39=(a33*a20);
  a38=(a38+a39);
  a34=sin(a34);
  a39=(a02*a34);
  a40=(a38*a39);
  a36=(a36+a40);
  a29=(a23*a29);
  a33=(a02*a33);
  a29=(a29+a33);
  a33=(a23*a34);
  a40=(a29*a33);
  a36=(a36+a40);
  if (res[0]!=0) res[0][0]=a36;
  a05=(a00*a05);
  a09=(a01*a09);
  a05=(a05+a09);
  a09=(a05*a14);
  a06=(a00*a06);
  a10=(a01*a10);
  a06=(a06+a10);
  a10=(a06*a17);
  a09=(a09+a10);
  a10=(a09*a19);
  a36=(a05*a15);
  a06=(a06*a11);
  a36=(a36+a06);
  a06=(a36*a08);
  a10=(a10+a06);
  a12=(a12*a00);
  a22=(a22*a01);
  a12=(a12+a22);
  a22=(a12*a24);
  a10=(a10+a22);
  a22=(a10*a26);
  a01=(a36*a28);
  a00=(a09*a18);
  a01=(a01-a00);
  a00=(a12*a30);
  a01=(a01+a00);
  a00=(a01*a31);
  a22=(a22+a00);
  a00=(a32*a36);
  a12=(a02*a12);
  a00=(a00+a12);
  a12=(a00*a13);
  a22=(a22+a12);
  a12=(a22*a35);
  a06=(a01*a37);
  a10=(a10*a25);
  a06=(a06-a10);
  a10=(a00*a20);
  a06=(a06+a10);
  a10=(a06*a39);
  a12=(a12+a10);
  a01=(a23*a01);
  a00=(a02*a00);
  a01=(a01+a00);
  a00=(a01*a33);
  a12=(a12+a00);
  if (res[0]!=0) res[0][1]=a12;
  a12=1.3548206757596562e-01;
  a00=(a12*a04);
  a10=9.9077979861929788e-01;
  a40=(a10*a03);
  a00=(a00+a40);
  a14=(a00*a14);
  a10=(a10*a04);
  a12=(a12*a03);
  a10=(a10-a12);
  a17=(a10*a17);
  a14=(a14+a17);
  a19=(a14*a19);
  a15=(a00*a15);
  a10=(a10*a11);
  a15=(a15+a10);
  a08=(a15*a08);
  a19=(a19+a08);
  a08=-3.6393374126056478e-06;
  a24=(a08*a24);
  a19=(a19+a24);
  a26=(a19*a26);
  a28=(a15*a28);
  a18=(a14*a18);
  a28=(a28-a18);
  a08=(a08*a30);
  a28=(a28+a08);
  a31=(a28*a31);
  a26=(a26+a31);
  a31=(a32*a15);
  a08=1.3368032756783181e-11;
  a31=(a31+a08);
  a13=(a31*a13);
  a26=(a26+a13);
  a13=(a26*a35);
  a37=(a28*a37);
  a19=(a19*a25);
  a37=(a37-a19);
  a20=(a31*a20);
  a37=(a37+a20);
  a39=(a37*a39);
  a13=(a13+a39);
  a28=(a23*a28);
  a31=(a02*a31);
  a28=(a28+a31);
  a33=(a28*a33);
  a13=(a13+a33);
  if (res[0]!=0) res[0][2]=a13;
  a13=0.;
  if (res[0]!=0) res[0][3]=a13;
  a33=(a02*a35);
  a31=(a38*a33);
  a39=(a27*a34);
  a31=(a31-a39);
  a23=(a23*a35);
  a35=(a29*a23);
  a31=(a31+a35);
  if (res[0]!=0) res[0][4]=a31;
  a31=(a06*a33);
  a35=(a22*a34);
  a31=(a31-a35);
  a35=(a01*a23);
  a31=(a31+a35);
  if (res[0]!=0) res[0][5]=a31;
  a33=(a37*a33);
  a34=(a26*a34);
  a33=(a33-a34);
  a23=(a28*a23);
  a33=(a33+a23);
  if (res[0]!=0) res[0][6]=a33;
  if (res[0]!=0) res[0][7]=a13;
  a33=(a32*a38);
  a29=(a02*a29);
  a33=(a33+a29);
  if (res[0]!=0) res[0][8]=a33;
  a29=(a32*a06);
  a01=(a02*a01);
  a29=(a29+a01);
  if (res[0]!=0) res[0][9]=a29;
  a32=(a32*a37);
  a02=(a02*a28);
  a32=(a32+a02);
  if (res[0]!=0) res[0][10]=a32;
  if (res[0]!=0) res[0][11]=a13;
  a13=1.0000000000000001e-01;
  a33=(a13*a33);
  a02=8.8258999999999996e-05;
  a27=(a02*a27);
  a28=-9.0999999999999998e-02;
  a38=(a28*a38);
  a27=(a27+a38);
  a38=-2.1984000000000000e-02;
  a16=(a38*a16);
  a01=-2.5074999999999997e-01;
  a21=(a01*a21);
  a16=(a16+a21);
  a21=2.8503000000000001e-01;
  a07=(a21*a07);
  a16=(a16+a07);
  a27=(a27+a16);
  a33=(a33+a27);
  if (res[0]!=0) res[0][12]=a33;
  a29=(a13*a29);
  a22=(a02*a22);
  a06=(a28*a06);
  a22=(a22+a06);
  a09=(a38*a09);
  a36=(a01*a36);
  a09=(a09+a36);
  a05=(a21*a05);
  a09=(a09+a05);
  a22=(a22+a09);
  a29=(a29+a22);
  if (res[0]!=0) res[0][13]=a29;
  a13=(a13*a32);
  a02=(a02*a26);
  a28=(a28*a37);
  a02=(a02+a28);
  a38=(a38*a14);
  a01=(a01*a15);
  a38=(a38+a01);
  a21=(a21*a00);
  a00=1.2300000000000000e-01;
  a21=(a21+a00);
  a38=(a38+a21);
  a02=(a02+a38);
  a13=(a13+a02);
  if (res[0]!=0) res[0][14]=a13;
  a13=1.;
  if (res[0]!=0) res[0][15]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int T_fk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int T_fk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int T_fk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void T_fk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int T_fk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void T_fk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void T_fk_incref(void) {
}

CASADI_SYMBOL_EXPORT void T_fk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int T_fk_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int T_fk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real T_fk_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* T_fk_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* T_fk_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* T_fk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* T_fk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int T_fk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int T_fk_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
